version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web:/go/src/work
    command: realize start --run
    tty: true
    ports:
      - 8088:80
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: 
      - app.env
    volumes: 
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306